passoffice = git
createimagemap = yes
compare = none
createhistory = no
gitpath = /Geonovum/IMG
sfconformance = 2
#mapping = MIM-NEN3610-ONTDUBBELD
assocbyreference        = yes
createmimformat = yes
mimformattype = xml
